export const ADD_NAME = `ADD_NAME`
export const UPDATE_TOKEN = `UPDATE_TOKEN`
export const UPDATE_LOGIN_STATUS = `UPDATE_LOGIN_STATUS`
export const UPDATE_ACTIVE_INDEX = `UPDATE_ACTIVE_INDEX`
export const UPDATE_ACTIVE_ITEM = `UPDATE_ACTIVE_ITEM`
export const UPDATE_ACTIVITY_LIST = `UPDATE_ACTIVITY_LIST`
